// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationServer.Infrastructure.Database;

#nullable disable

namespace ReservationServer.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260619030341_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationServer.Domain.Database.FlightBooking", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("text");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("FlightId", "SeatNumber");

                    b.ToTable("FlightBookings");
                });

            modelBuilder.Entity("ReservationServer.Domain.Database.FlightInstance", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("text");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("text");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlightNumber", "DepartureTime");

                    b.ToTable("FlightInstances");
                });

            modelBuilder.Entity("ReservationServer.Domain.Database.FlightSeatCount", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("text");

                    b.Property<int>("TotalSeatCount")
                        .HasColumnType("integer");

                    b.HasKey("FlightId");

                    b.ToTable("FlightSeatCounts");
                });

            modelBuilder.Entity("ReservationServer.Domain.Database.SeatLayout", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("text");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("text");

                    b.Property<int>("SeatClass")
                        .HasColumnType("integer");

                    b.HasKey("FlightNumber", "SeatNumber");

                    b.ToTable("SeatLayouts");
                });
#pragma warning restore 612, 618
        }
    }
}
