// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketServer.Infrastructure.Database;

#nullable disable

namespace TicketServer.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    partial class FlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketServer.Domain.Database.FlightBooking", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("text");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("FlightId", "SeatNumber");

                    b.ToTable("FlightBookings");
                });

            modelBuilder.Entity("TicketServer.Domain.Database.FlightInstance", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("text");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("text");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlightNumber", "DepartureTime");

                    b.ToTable("FlightInstances");
                });

            modelBuilder.Entity("TicketServer.Domain.Database.FlightSeatCount", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("text");

                    b.Property<int>("TotalSeatCount")
                        .HasColumnType("integer");

                    b.HasKey("FlightId");

                    b.ToTable("FlightSeatCounts");
                });

            modelBuilder.Entity("TicketServer.Domain.Database.SeatLayout", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("text");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("text");

                    b.Property<int>("SeatClass")
                        .HasColumnType("integer");

                    b.HasKey("FlightNumber", "SeatNumber");

                    b.ToTable("SeatLayouts");
                });
#pragma warning restore 612, 618
        }
    }
}
